### ISSUE TITLE
Failed to compile on dmd2.0.67 rc1

### ISSUE THREAD

**Issue by buggins** [Devisualization/image#3]
devisualization\image\png\reader.d(139): Error: cannot cast expression data[index..index + 4u] of type ubyte[] to ubyte[4]
devisualization\image\png\reader.d(140): Error: cannot cast expression data[index + 4u..index + 8u] of type ubyte[] to char[4]
